/**
 * Enhanced Offline Protocols with Clinical Reasoning Engine
 * Provides intelligent triage when backend AI is unavailable
 */

import ClinicalReasoningEngine from './reasoning_engine/index.js';

// Initialize reasoning engine
const reasoningEngine = new ClinicalReasoningEngine();
let engineInitialized = false;

/**
 * Perform offline triage using the Clinical Reasoning Engine
 * @param {Object} intake - Patient intake data
 * @returns {Object} Triage result
 */
export async function performOfflineTriage(intake) {
    console.log("🧠 Executing Enhanced Offline Triage with Reasoning Engine...");

    // Initialize engine if needed
    if (!engineInitialized) {
        await reasoningEngine.initialize();
        engineInitialized = true;
    }

    // Extract symptoms from intake
    const symptoms = extractSymptoms(intake);
    const vitals = extractVitals(intake);
    const age = extractAge(intake);

    // Run reasoning engine
    const analysis = await reasoningEngine.analyze({
        symptoms,
        vitals,
        age,
        history: intake.history || []
    });

    // Transform to expected format
    return {
        risk_tier: analysis.tier,
        reasoning: analysis.reasoning,
        danger_signs: analysis.dangerSigns,
        uncertainty: `${analysis.confidence}% confidence (OFFLINE MODE)`,
        recommended_actions: analysis.actions.map(a => a.action),
        first_aid_advice: analysis.actions.filter(a => a.priority === 'HIGH').map(a => a.action),
        monitoring_metrics: ["Temperature", "Breathing Rate", "Consciousness Level"],
        diagnosis: analysis.diagnosis,
        confidence: analysis.confidence,
        differential_diagnosis: analysis.differentialDiagnosis
    };
}

/**
 * Generate offline referral note
 * @param {Object} intake - Patient intake data
 * @param {Object} triage - Triage result
 * @returns {String} Formatted referral note
 */
export async function generateOfflineReferralNote(intake, triage) {
    console.log("📝 Generating Offline Referral Note...");

    const patientId = intake.patientId || 'PT-UNKNOWN';
    const date = new Date().toLocaleDateString('en-GB');
    const time = new Date().toLocaleTimeString('en-GB');

    // Extract vitals
    const vitals = extractVitals(intake);
    const age = extractAge(intake);

    // Build SOAP note
    let note = `═══════════════════════════════════════════════════
CLINICAL REFERRAL NOTE (OFFLINE GENERATED)
═══════════════════════════════════════════════════

Patient ID: ${patientId}
Date: ${date}
Time: ${time}
Generated by: FirstLine Offline Clinical Engine

───────────────────────────────────────────────────
SUBJECTIVE (Chief Complaint & History)
───────────────────────────────────────────────────

Chief Complaint:
${intake.chiefComplaint || 'Not specified'}

History of Present Illness:
${intake.symptoms || 'Patient presents with symptoms as documented below.'}

Duration: ${intake.duration || 'Not specified'}
Age: ${age ? `${age} years` : 'Not specified'}

───────────────────────────────────────────────────
OBJECTIVE (Vital Signs & Physical Exam)
───────────────────────────────────────────────────

Vital Signs:
• Temperature: ${vitals.temperature ? `${vitals.temperature}°C` : 'Not recorded'}
• Respiratory Rate: ${vitals.respiratoryRate ? `${vitals.respiratoryRate}/min` : 'Not recorded'}
• Heart Rate: ${vitals.heartRate ? `${vitals.heartRate} bpm` : 'Not recorded'}
• Blood Pressure: ${vitals.bloodPressure || 'Not recorded'}
• Oxygen Saturation: ${vitals.oxygenSat ? `${vitals.oxygenSat}%` : 'Not recorded'}

Physical Examination:
${intake.physicalExam || 'Examination findings as per clinical assessment.'}

───────────────────────────────────────────────────
ASSESSMENT (Clinical Diagnosis)
───────────────────────────────────────────────────

Primary Diagnosis: ${triage.diagnosis || 'Pending further evaluation'}
Triage Category: ${triage.risk_tier}
Confidence Level: ${triage.confidence}%

Clinical Reasoning:
${triage.reasoning}

${triage.danger_signs && triage.danger_signs.length > 0 ? `
⚠️ DANGER SIGNS IDENTIFIED:
${triage.danger_signs.map(s => `• ${s}`).join('\n')}
` : ''}

${triage.differential_diagnosis && triage.differential_diagnosis.length > 0 ? `
Differential Diagnosis (consider):
${triage.differential_diagnosis.map(d => `• ${d.diagnosis} (${d.confidence}% match)`).join('\n')}
` : ''}

───────────────────────────────────────────────────
PLAN (Treatment & Recommendations)
───────────────────────────────────────────────────

Immediate Actions:
${triage.first_aid_advice && triage.first_aid_advice.length > 0
            ? triage.first_aid_advice.map((a, i) => `${i + 1}. ${a}`).join('\n')
            : '1. Monitor patient closely\n2. Provide supportive care'}

Recommended Treatment:
${triage.recommended_actions && triage.recommended_actions.length > 0
            ? triage.recommended_actions.map((a, i) => `${i + 1}. ${a}`).join('\n')
            : 'Follow standard protocols for presenting condition'}

Monitoring Parameters:
${triage.monitoring_metrics ? triage.monitoring_metrics.map(m => `• ${m}`).join('\n') : '• Vital signs\n• Symptom progression'}

${triage.risk_tier === 'RED' ? `
🚨 URGENT REFERRAL REQUIRED
This patient requires immediate hospital evaluation and treatment.
Transport via ambulance if available.
` : triage.risk_tier === 'YELLOW' ? `
⚠️ PROMPT MEDICAL ATTENTION NEEDED
Patient should be seen by a clinician within 24 hours.
` : `
ℹ️ ROUTINE FOLLOW-UP
Patient may be managed with home care.
Advise to return if symptoms worsen.
`}

───────────────────────────────────────────────────
NOTES
───────────────────────────────────────────────────

This referral note was generated using FirstLine's offline
clinical decision support system based on WHO IMCI guidelines
and NHS clinical protocols.

⚠️ IMPORTANT: This is a computer-generated assessment.
Clinical judgment should always take precedence.
A qualified healthcare provider should review this patient.

═══════════════════════════════════════════════════
END OF REFERRAL NOTE
═══════════════════════════════════════════════════
`;

    return note;
}

/**
 * Helper: Extract symptoms from intake
 */
function extractSymptoms(intake) {
    const symptomsText = intake.symptoms || intake.chiefComplaint || '';

    // Split by common delimiters
    const symptoms = symptomsText
        .toLowerCase()
        .split(/[,;.\n]/)
        .map(s => s.trim())
        .filter(s => s.length > 2);

    return symptoms;
}

/**
 * Helper: Extract vitals from intake
 */
function extractVitals(intake) {
    return {
        temperature: intake.temperature || intake.temp || null,
        respiratoryRate: intake.respiratoryRate || intake.rr || null,
        heartRate: intake.heartRate || intake.hr || intake.pulse || null,
        bloodPressure: intake.bloodPressure || intake.bp || null,
        oxygenSat: intake.oxygenSat || intake.spo2 || null
    };
}

/**
 * Helper: Extract age from intake
 */
function extractAge(intake) {
    if (intake.age) return parseInt(intake.age);
    if (intake.dateOfBirth) {
        const dob = new Date(intake.dateOfBirth);
        const now = new Date();
        return Math.floor((now - dob) / (365.25 * 24 * 60 * 60 * 1000));
    }
    return null;
}

export default {
    performOfflineTriage,
    generateOfflineReferralNote
};
